### PR TITLE
reset job failed flag

### LINKED ISSUE #2: Reset job failed flag
Hi there!

We should reset a `job.opts[:failed]` flag here https://github.com/yabeda-rb/yabeda-schked/blob/197e5f1e552258b8eb10af2b92e4dd8f45d277b2/lib/yabeda/schked.rb#L41C17-L41C17

The reason is when an error was fired for the first time, we are constantly getting errors on our dashboard. It resets only after a pod restarting.
image

### PR DESCRIPTION
**Pull request by Arlantir**
- Fixed an error: if the job failed, the flag `job.opts[:failed]` was not reset, and metrics for the failed job continued to be sent.
- Fixed the test functionality.
- Refactored the tests.

fix #2

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -6,6 +6,7 @@
 /pkg/
 /spec/reports/
 /tmp/
+/.idea
```
Comment (Envek) [inline .gitignore]: Please don't include developer-specific things to project `.gitignore`. Set up your [global git ignore file](https://sebastiandedeyne.com/setting-up-a-global-gitignore-file/).
```suggestion
```

File: lib/yabeda/schked.rb [hunk 2]
```diff
@@ -41,6 +41,8 @@ def self.job_name(job)
       labels = {success: !job.opts[:failed], name: job_name(job)}
       Yabeda.schked.job_execution_runtime.measure(labels, job.last_work_time.round(3))
       Yabeda.schked.jobs_executed_total.increment(labels)
+
+      job.opts[:failed] = false
```
Comment (Envek) [inline lib/yabeda/schked.rb]: Probably good idea to place it under `ensure` for two reasons:
 1. to reset flag even in case if something errored in Yabeda itself
 2. to visually make this code as a cleanup code
```suggestion
    ensure
      job.opts[:failed] = false
```

File: CHANGELOG.md [hunk 3]
```diff
@@ -7,6 +7,17 @@ and this project adheres to [Semantic Versioning](http://semver.org/spec/v2.0.0.
 
 ## [Unreleased]
 
+## 0.2.1 (2024-04-05)
```
Comment (Envek) [inline CHANGELOG.md]: No need to bump version, I will do it on release. But thanks for CHANGELOG!

**Review by Envek — COMMENTED** [review]
Thanks for the pull request! Here are some minor suggestions (see individual comments below)

File: CHANGELOG.md (hunk 3 above)
Comment (bibendi) [reply CHANGELOG.md]: Andrey, hey! Can you make a release right after the PR has been merged?

Comment (Arlantir) [reply CHANGELOG.md]: Removed version update

**Review by Envek — APPROVED** [review]

**Comment by Envek** [comment]
Thank you very much! Released in [0.2.1](https://github.com/yabeda-rb/yabeda-schked/releases/tag/v0.2.1), enjoy!

**Comment by Arlantir** [comment]
Thanks
